if: (!cancelled())
122
      run: df -hT
123
​
124
    - name: Upload bin directory
125
      uses: actions/upload-artifact@main
126
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
127
      with:
128
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
129
        path: openwrt/bin
130
​
131
    - name: Organize files
132
      id: organize
133
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
134
      run: |
135
        cd openwrt/bin/targets/*/*
136
        rm -rf packages
137
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
138
        echo "::set-output name=status::success"
139
​
140
    - name: Upload firmware directory
141
      uses: actions/upload-artifact@main
142
      if: steps.organize.outputs.status == 'success' && !cancelled()
143
      with:
144
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
145
        path: ${{ env.FIRMWARE }}
146
​
147
    - name: Generate release tag
148
      id: tag
149
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
150
      run: |
151
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
152
        touch release.txt
153
        echo "Custom HomeLede Mod OpenWrt For Non-docker And Non-multimedia User" >> release.txt
154
        echo "Caution：Homeconnect Could Not Work In This Edition" >> release.txt
155
        echo "Enhanced: Adjust SmartDNS Configuration & Dnscrypt-proxy Configuration" >> release.txt
156
        echo "Enhanced: Add Some Drivers, Add Some Package" >> release.txt
157
        echo "::set-output name=status::success"
158
​
159
    - name: Upload firmware to release
160
      uses: softprops/action-gh-release@v1
161
      if: steps.tag.outputs.status == 'success' && !cancelled()
162
      env:
163
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
164
      with:
165
        tag_name: ${{ steps.tag.outputs.release_tag }}
166
        body_path: release.txt
167
        files: ${{ env.FIRMWARE }}/*
168
​
169
    - name: Delete workflow runs
170
      uses: GitRML/delete-workflow-runs@main
171
      with:
172
        retain_days: 1
173
        keep_minimum_runs: 3
174
​
175
    - name: Remove old Releases
176
      uses: dev-drprasad/delete-older-releases@v0.1.0
177
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
178
      with:
179
        keep_latest: 3
180
        delete_tags: true
181
      env:
182
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
